### PR TITLE
Fix jslint errors in lib/jx

### PR DESCRIPTION
**Pull request by brodybits**
The diff is pretty big. I used `tools/closure_linter/closure_linter/fixjsstyle.py` to fix a _lot_ of the errors, with a little rework to the changes, but also had to fix a number of issues by hand. I decided to break the changes into per-file commits, along with some multi-file commits.

There is still an issue on `lib/jx/_jx_marker.js` which I will deal with later.

If these changes are accepted, I am happy to work on the other Javascript files.

### CODE REVIEW

**Comment by ktrzeciaknubisa** [comment]
Looks like harmless formatting. Indents fixed, quotes replaced, etc. One might ask, if we're going to format other js sources as well (not just lib/jx) ?

I haven't run test against all this, @brodybits did you?

**Comment by brodybits** [comment]
> One might ask, if we're going to format other js sources as well (not just lib/jx) ?

As I said in the description:
> If these changes are accepted, I am happy to work on the other Javascript files.

> I haven't run test against all this, @brodybits did you?

I forgot to mention that I _did_ run the test suite (using `make test`) and no new errors are introduced.

@ktrzeciaknubisa @obastemur please confirm if you guys will accept them and I can fix the rest. I can also squash and/or rebase the changes so far if you want.

I have another remark that when I compared some of the Javascript files to Node 0.10.40, it _appears_ that they made some nice formatting fixes and I would like to include them here as well.  @obastemur @ktrzeciaknubisa can you guys confirm this?

**Comment by obastemur** [comment]
@brodybits  Sounds good. Merging. Thanks!

**Pull request merged**
