### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by gcampax**
Import dependencies from node v4.4.5 (current LTS stable).
In particular this will update openssl, which is a good idea for security.

Node itself is not updated, nor is libmozjs, which are bigger and harder to backport.

### CODE REVIEW

**Comment by obastemur** [comment]
Why 'don't strip binaries'?

**Comment by gcampax** [comment]
If you strip binaries, you lose debug symbols, and therefore you cannot debug any native code issue or crash.
If you don't strip binaries, ndk-build will still strip them, but it will keep an unstripped version in obj/local for debugging.
Anyway, that patch was not meant for this pull request. Not sure why github put it there.

**Comment by obastemur** [comment]
@gcampax can we fix the branch conflicts? @yaronyg any comment on these updates? Is there anyone to test these changes?

**Comment by yaronyg** [comment]
@enricogior Any comment on this? I know we already did an update to OpenSSL. Is this even newer?

**Comment by enricogior** [comment]
@yaronyg the only deps we updated in thaliproject/jxcore is OpenSSL, we used v1.0.1t to minimize the impact of the update. In this PR, OpenSSL is 1.0.2h.

**Comment by yaronyg** [comment]
@enricogior So ideally we would review this but realistically we just don't have the resources/time right now?

**Comment by enricogior** [comment]
@yaronyg yes, we don't have the resources right now. Also it would be more manageable to have dedicated PR for individual deps.

**Comment by gcampax** [comment]
Meanwhile I moved away from jxcore entirely, so I'm going to close this PR because I won't be working on it.
(If you care, I was using jxcore on Android, and I found a way to run native node instead. Code at https://github.com/Stanford-Mobisocial-IoT-Lab/thingengine-platform-android/blob/master/app/src/main/jni/node-launcher.cpp )

**Comment by quanganh206** [comment]
@gcampax 
Great to hear about your work and share. Do you have any plan with iOS?

**Comment by gcampax** [comment]
The project i"m working on uses node for a background service that continously run in the app, but iOS forbids that (regardless of what language you use), so on iOS we're probably going to use a thin client + web server architecture. Which in turn means I don't plan to work on porting node to iOS.
(Also I should say that no iOS code exists at the moment, and this is all speculation)

**Comment by quanganh206** [comment]
Thanks @gcampax for your valued information. With previous jxcore for cordova it can work with iOS too, I mean no background service here. Anyway, if you do not mind, please share news information whenever you have. I still looking for some solution like jxcore yet.

**Comment by enricogior** [comment]
@quanganh206 you may be interested in this: http://www.janeasystems.com/blog/node-js-meets-ios/

**Comment by quanganh206** [comment]
Thanks @enricogior so much!

**Pull request closed without merging**
