### PR TITLE
Some fixes for 0.3.1.0

### PR DESCRIPTION
**Pull request by brodybits**
Fixes so far (#585):

- Copied `test/simple/test-process-config.js` from Node 0.10.x/0.12.x (but kept the existing file header), now passes OK
- ~~Quick fix to `src/jx/jx_instance.cc` to get background jobs to work in default V8 build configuration and pass `test/simple/test-api-tasks.js`~~

UPDATE(s):
- fixed jslint errors

### CODE REVIEW

**Comment by brodybits** [comment]
Fixed JS_ENGINE_LOCKER macro in `src/jx/Proxy/V8_3_14/V8Environment.h` instead of the quick fix in `src/jx/jx_instance.cc`, as requested by @obastemur in this comment: https://github.com/jxcore/jxcore/issues/585#issuecomment-146961826

**Comment by brodybits** [comment]
Some more fixes:
- fix possible crash in `node_crypto.cc:EIO_PBKDF2After()` variants
- handle error message in test-domain.js in case of `--engine-v8-3-28` configure option (ref: #585)
- common.gypi: fix V8 host_arch & target_arch in the case of x64

**Comment by brodybits** [comment]
I will raise a new PR that addresses the comments by @obastemur when I get a chance. @obastemur it would really help me if you can answer my questions in response to your comments.

**Comment by obastemur** [comment]
@brodybits please skip `JS_ENGINE_LOCKER` and `commons.gypi` parts. 

`JS_ENGINE_LOCKER` is a bit messy ATM. I will try to combine `isolate` creations on a single place.

However you can push the initial fix you made prior to JS_ENGINE_LOCKER change. I didn't test that but that can be a good start point for me to move on.

Thanks!

**Comment by brodybits** [comment]
I rebased the changes except for the `JS_ENGINE_LOCKER` and `commons.gypi` changes (`test-domain.js` fix slightly different) and verified that they do not introduce any new `make test` failures when built for the default V8 engine, Mozilla JS engine, or new V8 engine. In summary, the following test cases are now working again on these engine:
- `test-crypto.js` no longer crashing (was crashing on the Mozilla JS engine)
- `test-crypto-binary-default.js` no longer crashing (was crashing on the new V8 engine)
- `test-domain.js` (was failing on the new V8 engine)
- `test-process-config.js`
- a number of `test-child-process-*` and `test-cluster-*` failures on the new V8 engine now fixed due to a small change in `tcp_wrap.cc`

There are no longer any failures on the Mozilla JS engine. `test-api-tasks.js` still fails on the default V8 engine since the `JS_ENGINE_LOCKER` fix is omitted. The following tests continue to fail on the new V8 engine (ref: #585):
- `test-event-emitter-memory-leak.js`
- `test-repl.js`
- `test-signal-handler.js`

Please let me know when you expect to merge these changes or if there is anything else you need me to do. Thanks for your attention!

**Comment by obastemur** [comment]
@brodybits Thanks!

**Comment by brodybits** [comment]
:+1: :+1:

**Pull request merged**
