### PR TITLE
Fix child process environmental variables

### PR DESCRIPTION
**Pull request by brodybits**
Passes test/simple/test-crypto-domains.js & test/simple/test-process-env.js

### CODE REVIEW

**Comment by obastemur** [comment]
@brodybits Thanks!

**Comment by ktrzeciaknubisa** [comment]
Guys, I'm not sure about this commit. We have been adding `if (env.hasOwnProperty(key))` for a reason (https://github.com/jxcore/jxcore/issues/287). 

Please note, that *test/simple/test-process-env.js* sets `process.env.hasOwnProperty` to string *asdf*. That is a reason for jx to fail. 

In my opinion it's better to add an extra check to the *child_process.js*: if `hasOwnProperty` is a function, so we would have:

```js
    if (typeof env.hasOwnProperty !== "function" || env.hasOwnProperty(key))
      envPairs.push(key + '=' + env[key]);
```

Also, shouldn't this PR go to 3.0.0.6?

**Comment by brodybits** [comment]
> ```Javascript
>     if (typeof env.hasOwnProperty !== "function" || env.hasOwnProperty(key))
>       envPairs.push(key + '=' + env[key]);
> ```

passes `test/simple/test-process-env.js` but breaks `test-child-process-env.js` which was also fixed by my change (I just fixed it in the description, my apologies).

A couple more remarks:

Considering that jxcore shares a codebase with node.js and provides node.js functionality, I suspect we should maintain as much compatibility as possible, which can be partially demonstrated by passing the same test suite. Or am I missing something?

For every new feature or bug fix (that goes beyond the scope of the original node.js project), I suspect we should (ideally) maintain tests to be reasonably sure the do not get broken, #287 for example, or am I mistaken somehow?

I am happy to push bug fixes to `master`, current release (`3.0.0.6`) or anywhere else you like. Can @jxcore owners specify this somewhere?

**Comment by obastemur** [comment]
current systematic is : better be 0.3.0.6 (always the latest pre-release) then (if it's okay) merge into master.

was my mistake merging into master. For this  particular issue, lets fix on master and I will rebase it back to 0.3.0.6

**Comment by ktrzeciaknubisa** [comment]
@brodybits I agree with you on compatibility and test maintaining matter.

One more check solves them all:

```js
if (typeof env.hasOwnProperty !== "function" || env.hasOwnProperty(key) || env.__proto__[key])
```

Or is there any more elegant solution?

**Comment by brodybits** [comment]
> ```Javascript
> if (typeof env.hasOwnProperty !== "function" || env.hasOwnProperty(key) || env.__proto__[key])
> ```

:+1: Do you want me to issue a PR with this?

**Comment by brodybits** [comment]
I just issued PR #532 to fix this. I would still like to see a test for #287 to make sure it doesn't get broken again. I will work on this if I get a chance.

**Pull request merged**
