### PR TITLE
ECDH crypto module ported from node 0.12.x

### PR DESCRIPTION
**Pull request by karaxuna**

### CODE REVIEW

**Comment by obastemur** [comment]
Can we also bring the test case?

**Comment by karaxuna** [comment]
@obastemur added

**Comment by obastemur** [comment]
@karaxuna  We also need the docs are updated from the original. 
Couldn't check yet, this passes the test case right ? (Chakra, SM, V8 ?)

**Comment by karaxuna** [comment]
I have tested on V8 only. OK, I'll add docs and check other engines too.

**Comment by brodybits** [comment]
This project is already using Travis CI, which _should_ test on both Spider Monkey and V8. If you look very carefully the Travis CI build is failing.

Also, I suggest we consider adding something like AppVeyor if it can test the Chakra version.

**Comment by karaxuna** [comment]
I shall fix bugs for firefox engine

**Pull request closed without merging**
