### PR TITLE
Conform to node-style callbacks

### PR DESCRIPTION
**Pull request by zamb3zi**
See #334.

### CODE REVIEW

**Comment by zamb3zi** [comment]
This includes updates to the tasks code and documentation. All of the old unit tests still pass, due to the deprecation handling I added. The relevant test cases generate deprecation warnings, for example:
```
>..\..\Release\jx.exe test-tasks-runOnThread.js
(jxcore.tasks) warning: Task callback functions now take two arguments (err, result). See https://goo.gl/dtWqpX.
```
If you accept this, I'll make another pull request to update the unit tests to the new callback style.

**Comment by zamb3zi** [comment]
The following now works. 
```javascript
var tasks = jxcore.tasks;
var Promise = require('bluebird');
Promise.promisifyAll(tasks);

var reverseTask = function(job) {
	return job.split('').reverse().join('');
};

tasks.addTaskAsync(reverseTask, 'testing')
	.then(function(result) {
		console.log(result);
	});
```
Note: `addTaskAsync` is not added in the pull request, it's automatically generated by `promisifyAll` now that `addTask` conforms to node-style callbacks.

**Comment by obastemur** [comment]
@zamb3zi looks good. Thanks! Just a minor change. Lets replace goo.gl links to longer ones ?

**Comment by zamb3zi** [comment]
Sure, @obastemur . Done that.

**Comment by obastemur** [comment]
@zamb3zi Thank you! for this remarkable contribution. We may really need the unit test cases and similar compatibility update to other parts of the jxcore.tasks.

**Comment by zamb3zi** [comment]
No problem @obastemur . It looks like @ktrzeciaknubisa has done this already in fe8071d61efd8c5ba147d6d4f782e3f6409c706c? Anything more for me to do with this?

**Comment by obastemur** [comment]
@zamb3zi Thank You!

**Pull request merged**
