### PR TITLE
0.3.0.5

### PR DESCRIPTION
**Pull request by obastemur**

### CODE REVIEW

**Comment by kzc** [comment]
@obastemur - just curious... regarding "use JS engine version instead of names", what's the motivation behind this?  Do you want to have many different engine versions in the source tree at the same time?

**Comment by obastemur** [comment]
@kzc Yes. It is most probably not needed for SpiderMonkey but different V8 versions / shims etc. will be covered. It doesn't have to be under the same source tree (branch) yet we need to reach to a point that we shouldn't spend much effort on switching among the engines and versions.

**Comment by kzc** [comment]
@obastemur Good idea putting each engine version abstraction wrapper in its own directory since they often have radically different APIs between minor versions.

Is it a longer term goal to get rid of the engine ifdef's from src/*.{cc,h} and relying only on the abstraction layer? Would be nice to have a runtime pluggable engine in the form of a shared library.

**Comment by obastemur** [comment]
> Is it a longer term goal to get rid of the engine ifdef's from src/*.{cc,h} and relying only on the abstraction layer? Would be nice to have a runtime pluggable engine in the form of a shared library.

Yes and No. It's a goal that we need to handle soon and keep it that way on a long term :)

**Pull request merged**
