### PR TITLE
0.3.0.5

### PR DESCRIPTION
**Pull request by obastemur**

### CODE REVIEW

**Comment by kzc** [comment]
Although the succinct code is correct, I withdraw my suggestion based on micro benchmarking:

    $ cat t.js
    function bench(fn) {
      var u = undefined;
      var iterations = 1e7;
      var time = process.hrtime();
      for (var i = 0; i < iterations; ++i) { fn(u); }
      var elapsed = process.hrtime(time);
      var ns = elapsed[0] * 1e9 + elapsed[1];
      console.log('%d ns: %s', ns, fn.toString());
    }
    bench(function(v) {return typeof v == 'undefined' || v === null});
    bench(function(v) {return v == null});
    bench(function(v) {return typeof v == 'undefined' || typeof v == 'null'});
    bench(function(v) {return v === undefined || v === null});

    $ jx -jsv
    Mozilla SpiderMonkey v34
    $ jx t.js 
    3915022 ns: function (v) {return typeof v == 'undefined' || v === null}
    51429470 ns: function (v) {return v == null}
    53450044 ns: function (v) {return typeof v == 'undefined' || typeof v == 'null'}
    52609154 ns: function (v) {return v === undefined || v === null}

    $ iojs -v
    v2.3.4
    $ iojs t.js 
    14797393 ns: function (v) {return typeof v == 'undefined' || v === null}
    49139784 ns: function (v) {return v == null}
    48403198 ns: function (v) {return typeof v == 'undefined' || typeof v == 'null'}
    55568913 ns: function (v) {return v === undefined || v === null}

**Comment by ktrzeciaknubisa** [comment]
Wow, it's interesting, that `typeof v == 'undefined'` is much faster than any of the rest. However probably comparing `typeof` result to "null" string is pointless, since `typeof null` returns "[object]" as I see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof).

Nice benchmark though :)

**Comment by kzc** [comment]
> comparing typeof result to "null" string is pointless

:) indeed. Corrected bench below and compared values other than just `undefined`.

> Wow, it's interesting, that typeof v == 'undefined' is much faster than any of the rest

It appears both V8 and SM optimized that specific case and not the `v == null` case. Go figure. You never know until you benchmark.

    $ cat t.js
    function bench(fn) {
      var types = [undefined, null, {}, [], 'foo', 123];
      var iterations = 1e7;
      var time = process.hrtime();
      for (var t = 0; t < types.length; ++t) {
        var type = types[t];
        for (var i = 0; i < iterations; ++i) {
          fn(type);
        }
      }
      var elapsed = process.hrtime(time);
      var ns = elapsed[0] * 1e9 + elapsed[1];
      console.log('%j ns: %s', ns, fn.toString());
    }
    bench(function(v) {return typeof v == 'undefined' || v === null});
    bench(function(v) {return v == null});
    bench(function(v) {return v === undefined || v === null});

    $ jx -jsv
    Mozilla SpiderMonkey v34
    $ jx t.js 
    39232455 ns: function (v) {return typeof v == 'undefined' || v === null}
    393382871 ns: function (v) {return v == null}
    385048947 ns: function (v) {return v === undefined || v === null}

    $ iojs -v
    v2.3.4
    $ iojs t.js 
    81193007 ns: function (v) {return typeof v == 'undefined' || v === null}
    327643652 ns: function (v) {return v == null}
    355042318 ns: function (v) {return v === undefined || v === null}

I suspect the numbers in Duktape would be the opposite but building it required more dependencies than I was willing to apt-get.

**Comment by kzc** [comment]
duktape 1.2.2 timings for 1e7 iterations:

    13.738s: function(v) {return typeof v == 'undefined' || v === null}
    11.754s: function(v) {return v == null}
    18.141s: function(v) {return v === undefined || v === null}

`v == null` was fastest for this interpreted ECMAscript engine, but curiously not significantly faster than `typeof v == 'undefined' || v === null`

**Pull request merged**
