### PR TITLE
Efficiently repair reading of signed files

### PR DESCRIPTION
**Pull request by Gray1989**
This change makes use of garbage bytes (16) at the end of the file as
information to locate the required data to load for a native executable
efficiently. Additionally, it contains an efficient algorithm to look
for a the signature at the end of a signed file, if necessary, and
skipping it directly to the intended last byte of the file. The maximum
data size and custom offset using this algorithm are 4GB and the maximum
signature size at the end of the file is 10KB.

### CODE REVIEW

**Comment by Gray1989** [comment]
@ktrzeciaknubisa I'm sorry about giving you unreliable code the first time, I hope this makes up for it :)

**Comment by Gray1989** [comment]
Here is a screenshot of one of the performance tests I ran for my rewrite of `binaryFileIndexOf`:

image

**Comment by Gray1989** [comment]
I just wanted to give the code one last full checkover and I realize that I left an if statement behind that was supposed to pre-check a variable before entering the loop for added efficiency (so it wouldn't have to do the check over again inside the loop). I will fix it later though I'm really going to bed this time. Let me know what you think though please.

**Comment by Gray1989** [comment]
Another thing to note, the distributed release executable will be signed and therefore will not work for rebuilding the application and then signing. The application will work but signing will fail. There is a python script that I found which can remove the digital signature from a file. But it needs to be removed on the actual JX executable, before compiling if I remember correctly. Maybe somehow the JX executable can be loaded into a buffer and modified from there instead of copied and modified from the local drive. The digital signature can then be removed using the buffer and all of the read/write operations can occur in-memory as opposed to directly to the file on-disk for increased compilation performance. Then the file can simply be written to disk from the buffer when it's complete. If not able to be done completely in-memory at least a good portion of it can be. Just a thought.

**Comment by Gray1989** [comment]
I'm sorry for all of the commits. I always seem to feel as though nothing is ever really good enough. Plus I was kind of rushing myself to get the first commit in. I'll try to be more thoughtful about the code before I post it in the future.

**Comment by ktrzeciaknubisa** [comment]
@Gray1989 Thank you very much for the stuff. It really does work. I've tested on multiple platforms/engines. 

However I'd like to ask you for two things:

1. Could you re-post the PR for branch 0.3.1.0 ? That's the one we're currently working on and it also already has some *_jx_package.js* modifications.
2. Let's skip `binaryFileIndexOf` update for the moment unless there is no bug there. From what I understood it contains only optimization steps (milliseconds). We might take it later separately. 
3. Please try to keep as little commits as possible :)

Thank you!

**Comment by obastemur** [comment]
No repost is neeeded. I will merge it.

Is this good to go ?

**Comment by ktrzeciaknubisa** [comment]
Yes, except that:

> 0.3.1.0 already has some _jx_package.js modifications.

And they are not here under PR.
But after you merge I'm going to check them.

**Comment by obastemur** [comment]
@Gray1989 The commit history for this PR looks really mixedup. Can you squash them or PR a clean one?

**Comment by Gray1989** [comment]
@obastemur I've been trying to figure out how to squash them but I'll just create a new one. Sorry for any inconvenience.

**Pull request closed without merging**
