### PR TITLE
cork and uncork methods added in writable stream

### PR DESCRIPTION
**Pull request by karaxuna**
[Adding methods from node v0.12.7 issue](https://github.com/jxcore/jxcore/issues/571)

Added `Writable.cork` method that forces buffering of all writes. [See docs](http://nodejs.org/dist/v0.12.7/docs/api/stream.html#stream_writable_cork).
Added `Writable.setDefaultEncoding` method. [See docs](http://nodejs.org/dist/v0.12.7/docs/api/stream.html#stream_writable_setdefaultencoding_encoding)
Added `path.isAbsolute` method. [See docs](https://nodejs.org/docs/latest-v0.12.x/api/path.html#path_path_isabsolute_path)
Added `lookup` event when calling `socket.connect` (triggers after `dns.lookup`). [See docs](https://nodejs.org/docs/latest-v0.12.x/api/net.html#net_event_lookup)
Added `reset` event to repl. Triggers when calling `.clear` from repl client. [See docs](https://nodejs.org/docs/latest-v0.12.x/api/repl.html#repl_event_reset)
Added `Writable._writev` method. [See docs](http://nodejs.org/dist/v0.12.7/docs/api/stream.html#stream_writable_writev_chunks_callback)

### CODE REVIEW

**Comment by ktrzeciaknubisa** [comment]
Generally it looks ok. Except that node's test using `cork()` / `uncork()` [simple/test-stream-writev.js](https://github.com/nodejs/node/blob/v0.12.7-release/test/simple/test-stream-writev.js) (taken from node 0.12.7) fails:

```js
AssertionError: Should not call _write
```

I've run the same test against node 0.12.7 (downloaded from [here](https://nodejs.org/dist/v0.12.7/)) and it runs fine.

I haven't find out yet why this happens. @karaxuna Do you have any idea?

**Comment by karaxuna** [comment]
When calling `uncork`, `clearBuffer` method is called. If there are chunks in buffer, then node calls `stream._writev` method and passes all the chunks in buffer, instead of calling `_write` several times

```
w._writev = function(chunks, cb) {
    //...
};
```

Currently I have not yet implemented `_writev` method. That's why some tests not pass.

**Comment by karaxuna** [comment]
@ktrzeciaknubisa I think now tests pass

**Comment by ktrzeciaknubisa** [comment]
Yeap, it does :) Thanks.

But looks like now two of old tests start to fail and in both cases it's related to streams:

```bash 
Path: simple/test-crypto.js
TypeError: str.read(...) is null 
(/Users/nubisa_krzs/Documents/GitHub/karaxuna/jxcore/test/simple/test-crypto.js 272:17)
    at  (/Users/nubisa_krzs/Documents/GitHub/karaxuna/jxcore/test/simple/test-crypto.js:272:18)
```

```bash                                              
Path: simple/test-stream2-transform.js
# writable side consumption
# passthrough
TypeError: pt.read(...) is null 
(/Users/nubisa_krzs/Documents/GitHub/karaxuna/jxcore/test/simple/test-stream2-transform.js 85:10)
    at  (/Users/nubisa_krzs/Documents/GitHub/karaxuna/jxcore/test/simple/test-stream2-transform.js:85:11)
```

**Comment by karaxuna** [comment]
After executing this code:

```javascript
var pt = new PassThrough();
pt.write(new Buffer('foog'));
pt.write(new Buffer('bark'));
pt.write(new Buffer('bazy'));
pt.write(new Buffer('kuel'));
pt.end();
pt.read(20); // is null. works if you specify exact length: `pt.read(16)`
```

`pt._readableState.ended` is true when executing with nodejs or older jxcore. With current version, it is false, so `howMuchToRead` function returns 0 instead of `state.length` (16 in this case):

```javascript
if (n > state.length) {
  if (!state.ended) {
    state.needReadable = true;
    return 0;
  } else
    return state.length;
}
```

Can't figure out why `state.ended` is different with my code.

**Comment by ktrzeciaknubisa** [comment]
Maybe this will help you: it looks like in node/current jxcore `pt.end()` calls also `_stream_readable.js:readableAddChunk()` and passes null `chunk` which allows to call `onEofChunk()` and set `state.ended` to true (https://github.com/jxcore/jxcore/blob/0.3.1.0/lib/_stream_readable.js#L121) 

Here with cork implemented it doesn't, so the `state.ended` stays false. 

I'm not sure whether some more *stream_writable.js* or *stream_readable.js* changes need to be also included for this to work?

**Comment by karaxuna** [comment]
@ktrzeciaknubisa I think now it's fixed

**Comment by obastemur** [comment]
@karaxuna can you also bring the relevant tests from 0.12 ?

**Comment by obastemur** [comment]
@ktrzeciaknubisa merge if it's good to go

**Comment by ktrzeciaknubisa** [comment]
Yeap, I've just completed the tests and looks alright. Thanks @karaxuna . Merging

**Pull request merged**
