### PR TITLE
_cmp() accept buffer

### PR DESCRIPTION
**Pull request by karaxuna**

### CODE REVIEW

**Comment by ktrzeciaknubisa** [comment]
Thanks @karaxuna . It works. However please revert *_jx_package.js* edit, since it would be valid only if opposite logic would be applied for package execution/extraction (it still expects base64 string). Anyway this is on my side to take care of that part. The main thing is that `_cmp()` works with buffers now, and that's great.

**Comment by karaxuna** [comment]
@ktrzeciaknubisa Reverted _jx_package.js edit

**Comment by ktrzeciaknubisa** [comment]
But now we have also unnecessary *icu_config.gypi* modification :)

**Comment by karaxuna** [comment]
@ktrzeciaknubisa it must have been modified on build. Shall this file be in .gitignore?

**Comment by ktrzeciaknubisa** [comment]
I'm not sure, but anyway the target file contents seem to be the same. I'm merging. Thank you!

**Pull request merged**
