### PR TITLE
Fix git URL

### PR DESCRIPTION
**Pull request by sonnyp**

### CODE REVIEW

**Comment by ktrzeciaknubisa** [comment]
Thanks for repository name fix. However maybe let's better keep to the https:// protocol 
> git clone https://github.com/jxcore/jxcore.git`)

since I'm afraid your solution:
> git clone git@github.com:jxcore/jxcore.git` 

may fail on some platforms. For example it did not work on my OSX: *Permission denied (publickey).*

**Comment by alsotang** [comment]
https asscess seems more general than ssh access.

**Comment by sonnyp** [comment]
done

**Comment by ktrzeciaknubisa** [comment]
Thanks!

**Pull request merged**
