### PR TITLE
Safe Block function that can handle different closures

### PR DESCRIPTION
**Pull request by xtelinco**
The old safeBlock requires the same closure for to be used every time. This is OK if you are only incrementing a counter, but say if you wanted to add a random value to a value in the memory store and always get the correct total, I cannot get it to work correctly.

One of the commit logs contains a function that demonstrates the bug.

This is pretty much a complete rewrite, and javascript isn't my forte, so shout if something doesn't look correct. It seems to work ok, although do you think it will break anything?

### CODE REVIEW

**Comment by obastemur** [comment]
ping @ktrzeciaknubisa

**Comment by ktrzeciaknubisa** [comment]
@xtelinco Thanks a lot for this fix. It really does the job. 

However it looks like the original implementation missed the blockTimeout check, while the sync version `safeBlockSync()` has it.

Would you like to add also this check into your pull request?
***
However before doing that, we should redefine, how the timeout should work. Looking at how it is done in `safeBlockSync()`, I have my doubts and want to share with you.

The [docs](https://github.com/jxcore/jxcore/blob/master/doc/api/jxcore-store.markdown#storesharedsetblocktimeout) are stating for `setBlockTimeout()`:

> Sets the maximum time (milliseconds) during which the key in a safeBlock is locked. By default its value is 10000 milliseconds. When it elapses, JXcore automatically unlocks the key for other threads access.

However current implementation of  `safeBlockSync()` does not exactly do it. For single  `safeBlockSync()` it does not even trigger the timeout. 

Test: timeout set to 6 secs, while taks lasts for 10 secs. Timeout not triggered:

```js
var method = function(str) {
  jxcore.store.shared.safeBlockSync("myNumber", function () {
    // block for 10 secs
    var t0 = Date.now();
    while (Date.now() < t0 + 10000) {}
    console.log("finished after", str, Date.now() - t0, "ms");
  });
};

jxcore.store.shared.setBlockTimeout(6000);
jxcore.tasks.addTask(method, "first call");
```
The timeout would be triggered only once we would make another call of `safeBlockSync()`. Let's call it after the above block:

```js
setTimeout(function() {
  jxcore.tasks.addTask(method, "second call");
}, 3000);
```

Now the `blockTimeout` will trigger, but within 6 sec (timeout value) **starting from beginning of `second call`**, instead of beginning of `first call`. It's in the code [_jx_memStore.js#L178](https://github.com/jxcore/jxcore/blob/master/lib/jx/_jx_memStore.js#L178):

```js
 if (!$uw.setSourceIfEqualsToOrNull("+" + name, pid + "", "-5")) {
    var dtBas = Date.now();
   ...
}
```

This gives total 9 sec starting from 'first call', so that means, that key was locked 9 secs, instead of just 6 (although it was 6 for a 'second call').

So the timeout **does not lock the key for X ms**. How it is now, it defines for **how long the new `setBlockSync()` call waits, until will force the key to be unlocked.**

**Comment by xtelinco** [comment]
Ok. I will work on that.

Cheers,

Rob

**Comment by xtelinco** [comment]
I think this change does the trick. 

Thinking it through though, do you think we need to be able to support asynchronous calls within a block? To do it fully I think we would have to pass a callback function to the block function. That callback would be called once the block function had finished its asynchronous calls, which would then release the lock. Maybe its not needed yet, or maybe too complicated. 

Another method could be to pass two functions to the block function. One to hold the lock on return from the block function, and the other to release it once the async calls are finished. This way we maintain backward compatibility. If the hold lock function isn't called it operates the same as it is now. 

Thoughts?

**Comment by obastemur** [comment]
`do you think we need to be able to support asynchronous calls within a block? `

This can be unnecessarily complicated. I'm not sure if we could make it entirely stable in any future. Maybe we can work on the use cases and introduce something else? 

@xtelinco Thanks for this great contribution. 

LGTM, @ktrzeciaknubisa ping!

**Comment by xtelinco** [comment]
I agree, it does make it more complicated, and it is workable for a developer as it is now. 

I don't personally have a use case for it now, so maybe we should leave it for now.

**Comment by ktrzeciaknubisa** [comment]
Thanks @xtelinco . It does the job. I'm merging.

**Pull request merged**
