### PR TITLE
0.3.0.6

### PR DESCRIPTION
**Pull request by obastemur**

### CODE REVIEW

**Comment by brodybits** [comment]
The `0.3.0.6` branch does pass the test suite (except for the failure I already reported in #529). Please merge ASAP thanks!

**Comment by obastemur** [comment]
> Yes, the fix was necessary, otherwise there was a parse exception.

How about the cases i.e. package.json is asset ? Don't know if we have the test cases for each use case?

**Comment by ktrzeciaknubisa** [comment]
Those two calls are made: one before decompression and one after. The same way are treated files  extracted to the filesystem from the package. 

> How about the cases i.e. package.json is asset ? 

Allright, I'll check it too.

> Don't know if we have the test cases for each use case?

Maybe not yet. I'll add.

**Comment by ktrzeciaknubisa** [comment]
> I find it strange that you are repeating `new Buffer(source, 'base64').toString()` here.

I agree. There is an idea to get rid of all this: https://github.com/jxcore/jxcore/issues/508.

**Comment by obastemur** [comment]
@ktrzeciaknubisa you can merge this as soon as we are sure on module / package.json update

**Comment by ktrzeciaknubisa** [comment]
Alright, module / package.json checked for both assets and files. On Windows too. This 2388bd4beac0e8ef8450583643d34da22fc2d749 and this 6180b3d547f0f0e957283f2283768c46b1c300a5.

**Pull request merged**
