### PR TITLE
allow require('.')

### PR DESCRIPTION
**Pull request by martinies**
Fix for a reported issue io#1178. It also works for JXcore packaging.

issue:
require(".") should load ./index.js

### CODE REVIEW

**Comment by obastemur** [comment]
Looks good apart from using Array for a Dictionary kind of search. I think you wanted to make it something easily extendable. Please fix that part.

**Comment by obastemur** [comment]
We can stick with the original if check though. I don't see this part is getting more complicated.

**Comment by martinies** [comment]
updated accordingly. Anyway credit goes to @targos

**Comment by obastemur** [comment]
look okay. Thanks!

**Pull request merged**
