### PR TITLE
fs extension: async fs.readFile() and fs.exists()

### PR DESCRIPTION
**Pull request by ktrzeciaknubisa**
This is my proposal for async extension methods of `fs` module: `fs.readFile()` and `fs.exists()`. It was tested for both **desktop** and **android** application.

Below is code for testing on desktop:

```js
var ext = {
  exists : function(path, cb) {
    cb(path === dummy_file);
  },
  readFile : function(path, options, cb) {
    var cb = cb || options;

    if (path === dummy_file) {

      // async operation
      setTimeout(function() {
        cb(false, "contents of dummy file");
      }, 500);
      return;
    }

    cb(true);
  }
};

var fs = require("fs");
var dummy_file = "dummy_file.txt";
fs.setExtension("extensions", ext);

fs.exists(dummy_file, function(exists) {
  console.log("exists?", exists);
});

fs.readFile(dummy_file, { opt : true } , function(err, data) {
  console.log("readFile: isErr?",  err, "data:", data ? data.toString() : null);
});
```

### CODE REVIEW

**Comment by obastemur** [comment]
Some questions and change requests below;

1 - Why ` var _args = JSON.parse(JSON.stringify(args));` ?
2 - We add our extensions after `/** JXCORE_JXP* */` line. Before that line you should also define an empty version of your new function. Assume jxcore may give out the sources between line 0 and `/** JXCORE_JXP* */` . Your empty function shouldn't fail. This is necessary for the modules monkey patching the node's fs. 
3 - We need the test case (for multiple scenarios)

**Comment by ktrzeciaknubisa** [comment]
All right, the changes are ready.

The test cases should cover all scenarios related with those two methods: `fs.readFile()` and `fs.exists()`.
It also checks if extension method is not breaking reading of real files/folders located under file system or packaged.

**Comment by plika** [comment]
My initial review;

line 2145: for (var o in NativeModule.Roots) {
looks problematic. At least better check for hasOwnProperty.

line 2377: I didn't understand the implementation. Why setTimeout instead process.nextTick? or 0 ?

Is this implementation going to take care of *write* methods ?

**Comment by ktrzeciaknubisa** [comment]
Thanks @plika .

I do agree with both comments. However the exact usages can be found all over the whole project. We're already iterating objects with `for..in` at large scale: #287, but your note about `hasOwnProperty` is reasonable (as a side note, that fragment is already committed on jxcore master 00d0af43f660d9e80d23125b0b3295f89379a440 and applies to something else - it is just the pull request was created before that and so it is shown here as well). 

As for setTimeout(..., 0) - it's also known in our code. Even native `fs.readFile()` uses that once (line 197). Still `process.nextTick()` would fit, too.  

As for write methods - they are scheduled for one of the next steps. I cannot tell for sure at the moment, that proposed `callExtensions_async()` would support them in current shape, but that is an assumption.

**Comment by ktrzeciaknubisa** [comment]
Review comments are applied now.

**Comment by ktrzeciaknubisa** [comment]
I needed to rollback `hasOwnProperty()` update as it was generating a conflict and made pull request not mergeable automatically and as I mentioned before - it was related with some other issue that extensions here. I'll remember to apply this back on jxcore master.

**Pull request closed without merging**
