### PR TITLE
Bug Fix - Issue 240 -Deadlock when expiring items out of the memory store

### PR DESCRIPTION
**Pull request by xtelinco**
When expiring items out of the memory store, the locks are taken in the wrong order.
The modifier functions in src/wrappers/memory_wrap.cc take the locks in the reverse
order to this function, hence causes a race condition which can end in two threads
holding and waiting for a lock that the other holds.

Modified this function so that the timers lock is taken first, collects a list
of keys to delete, releases the timer lock and takes the store lock. The
result being that a dead lock is impossible.

Tested on a machine running jx core under high load. Dead lock has now not occurred for
72 hours. Previously dead locks occurred every 6 hours.

### CODE REVIEW

**Comment by xtelinco** [comment]
Out of interest, why do you stop looking once you have found an item to expire? There could be others, couldn't there?

I have left my implementation that would support the deleting of multiple keys. Obviously we would need to sort out your iterators, but this should be fairly simple to do within the same loop.

Am I missing something?

**Comment by obastemur** [comment]
It's something left from the initial implementation though. Very good catch! Would you like to contribute on that part too ? 

This one looks clear. Thanks for the fix and all the testing efforts!

**Comment by xtelinco** [comment]
I think I found out why that loop was coded to only erases one item at a time. btree_map doesn't work the same way as std::map, hence erasing multiple items in a loop has to be done differently. I think I have worked it out now, and the new code is in test. I will create a pull request in a couple of days if all is well.

I also have a fix for some javascript code. The function in question is safeBlock which I have stopped using in my development, as I can't get it to work as I feel correctly. Maybe it is working fine for you, but do you want to see my thoughts on that one as well? It doesn't work in the way I think it should.

**Comment by obastemur** [comment]
You are right, that's the case (kind of stability over performance) but I think it's time to make that part right! 

Just make sure we switch back to std::map for iOS builds (it's not going to stay this way but I have to check couple of edge cases there first). However, as long as you default btree it should be fine.

Surely you can bring into table anything 'reasonable' you expect from node.js / jxcore. Besides, memory store feature is widely open for ideas and contributions.  We can together figure out the problems with the additional use cases.

Thanks for your help!

**Pull request merged**
