### PR TITLE
Added arch build scripts

### PR DESCRIPTION
**Pull request by MarcMcIntosh**

### CODE REVIEW

**Comment by obastemur** [comment]
@MarcMcIntosh the only problem I see is the future maintenance of this script. Any idea?

**Comment by MarcMcIntosh** [comment]
Hi I maintain a couple of versions anyway one for the aur, and one for arm.... Talking about maintenance, how do you get around the shared header in /usr/lib/node... between jxcore-sm and node ? i kind of want to sort that out  :)

**Comment by obastemur** [comment]
@MarcMcIntosh `shared header` ?

**Comment by obastemur** [comment]
BTW; Thanks for the good work here.

**Comment by MarcMcIntosh** [comment]
Thanks obastemur, happy to do it :)
yeah I was installing jxcore and the last message to show up was along the lines of "file /usr/lib/node****.h already exists" I ended up uninstalling node and reinstalling it using node version managment. Which works fine now

**Comment by MarcMcIntosh** [comment]
exact output:
:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                              [--------------------------------] 100%
(1/1) checking package integrity                            [--------------------------------] 100%
(1/1) loading package files                                 [--------------------------------] 100%
(1/1) checking for file conflicts                           [--------------------------------] 100%
error: failed to commit transaction (conflicting files)
jxcore: /usr/include/node/ares.h exists in filesystem
jxcore: /usr/include/node/ares_version.h exists in filesystem
jxcore: /usr/include/node/common.gypi exists in filesystem
jxcore: /usr/include/node/config.gypi exists in filesystem
jxcore: /usr/include/node/nameser.h exists in filesystem
jxcore: /usr/include/node/node.h exists in filesystem
jxcore: /usr/include/node/node_buffer.h exists in filesystem
jxcore: /usr/include/node/node_internals.h exists in filesystem
jxcore: /usr/include/node/node_object_wrap.h exists in filesystem
jxcore: /usr/include/node/node_version.h exists in filesystem
jxcore: /usr/share/man/man1/node.1.gz exists in filesystem
Errors occurred, no packages were upgraded.

**Comment by obastemur** [comment]
I see. Two things to fix. First we may replace target folder naming to `jxcore` instead of `node`. Second, copying the headers inside `src/public` is enough for jxcore. Do you have time to contribute this change ? (makefile, configure etc. update)

**Comment by MarcMcIntosh** [comment]
hi man, I managed a slightly diffrent work around a few days ago.... which is just an additonal install script that pacman runs when installing. Will update just now :)

**Pull request merged**
